name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: '14'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - run: npm ci
      - run: npm test
